export const GET_DATA = 'GET_DATA';
export const GET_DATA_FULFILLED = 'GET_DATA_FULFILLED';
export const GET_DATA_REJECTED = 'GET_DATA_REJECTED';

export const UPDATE_DATA = 'UPDATE_DATA';
export const UPDATE_DATA_FULFILLED = 'UPDATE_DATA_FULFILLED';

export const PAUSE_FETCHING = 'PAUSE_FETCHING';
export const RESUME_FETCHING = 'RESUME_FETCHING';
